///////////////////////////////////////////////////////////////////////////////
// File generated by HDevelop for HALCON/C++ Version 25.11.0.0
// Non-ASCII strings in this file are encoded in local-8-bit encoding (cp936).
// Ensure that the interface encoding is set to locale encoding by calling
// SetHcppInterfaceStringEncodingIsUtf8(false) at the beginning of the program.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
///////////////////////////////////////////////////////////////////////////////
#include "HalconCpp.h"
#include "HDevThread.h"



using namespace HalconCpp;

// Procedure declarations 
// Chapter: Develop
// Short Description: Open a new graphics window that preserves the aspect ratio of the given image. 
extern void dev_open_window_fit_image (HObject ho_Image, HTuple hv_Row, HTuple hv_Column, 
    HTuple hv_WidthLimit, HTuple hv_HeightLimit, HTuple *hv_WindowHandle);
// Chapter: Develop
// Short Description: Switch dev_update_pc, dev_update_var, and dev_update_window to 'off'. 
extern void dev_update_off ();
// Local procedures 
void Preprocess_Color (HObject ho_Image, HObject *ho_ColorROI);
void Preprocess_Gray (HObject ho_Image, HObject *ho_GrayROI, HObject *ho_LeftGrayROI, HObject *ho_RightGrayROI);

// Procedures 
// Local procedures 
void Preprocess_Color (HObject ho_Image, HObject *ho_ColorROI)
{

  //============================================
  //Procedure: Preprocess_Color
  //Input :  Image  (3-channel color)
  //Output:  ColorROI  (preprocessed color image)
  //============================================

  //TODO: 彩色图预处理实现
}

void Preprocess_Gray (HObject ho_Image, HObject *ho_GrayROI, HObject *ho_LeftGrayROI, HObject *ho_RightGrayROI)
{

  // Local iconic variables
  HObject  ho_Gray, ho_RegionBlackRaw, ho_RegionBlackOpen;
  HObject  ho_RegionBlackConnAll, ho_RegionBlackValid, ho_RegionBlackUnion;
  HObject  ho_BandLeft, ho_BandRight, ho_BandTop, ho_BandBottom;
  HObject  ho_LeftCand, ho_RightCand, ho_TopCand, ho_BottomCand;
  HObject  ho_LeftConn, ho_RightConn, ho_TopConn, ho_BottomConn;
  HObject  ho_LeftSel, ho_RightSel, ho_TopSel, ho_BottomSel;
  HObject  ho_LeftMax, ho_RightMax, ho_TopMax, ho_BottomMax;
  HObject  ho_ROI_Middle, ho_GrayROI_Domain;

  // Local control variables
  HTuple  hv_BlackLow, hv_BlackHigh, hv_BandLeftRatio;
  HTuple  hv_BandRightRatio, hv_BandTopRatio, hv_BandBottomRatio;
  HTuple  hv_DefaultRow1Ratio, hv_DefaultRow2Ratio, hv_DefaultCol1Ratio;
  HTuple  hv_DefaultCol2Ratio, hv_OpenSize, hv_BorderMargin;
  HTuple  hv_MinBorderArea, hv_MinROIHeight, hv_MinROIWidth;
  HTuple  hv_IsFallback, hv_Channels, hv_Width, hv_Height;
  HTuple  hv_LeftNum, hv_RightNum, hv_TopNum, hv_BottomNum;
  HTuple  hv_ROI_Row1, hv_ROI_Row2, hv_ROI_Col1, hv_ROI_Col2;
  HTuple  hv_LR1, hv_LC1, hv_LR2, hv_LC2, hv_RR1, hv_RC1;
  HTuple  hv_RR2, hv_RC2, hv_TR1, hv_TC1, hv_TR2, hv_TC2;
  HTuple  hv_BR1, hv_BC1, hv_BR2, hv_BC2;

  //============================================
  //Procedure: Preprocess_Gray
  //Input :  Image
  //Output:  GrayROI / LeftGrayROI / RightGrayROI
  //============================================

  //---------- 参数区 ----------
  hv_BlackLow = 0;
  hv_BlackHigh = 16;

  hv_BandLeftRatio = 0.15;
  hv_BandRightRatio = 0.15;
  hv_BandTopRatio = 0.18;
  hv_BandBottomRatio = 0.18;

  hv_DefaultRow1Ratio = 0.22;
  hv_DefaultRow2Ratio = 0.78;
  hv_DefaultCol1Ratio = 0.10;
  hv_DefaultCol2Ratio = 0.90;

  hv_OpenSize = 5;
  hv_BorderMargin = 5;
  hv_MinBorderArea = 300;

  hv_MinROIHeight = 150;
  hv_MinROIWidth = 250;

  hv_IsFallback = 0;

  //---------- 转灰度 ----------
  CountChannels(ho_Image, &hv_Channels);
  if (0 != (int(hv_Channels>1)))
  {
    Rgb1ToGray(ho_Image, &ho_Gray);
  }
  else
  {
    ho_Gray = ho_Image;
  }

  GetImageSize(ho_Gray, &hv_Width, &hv_Height);

  //---------- 提取黑边 ----------
  Threshold(ho_Gray, &ho_RegionBlackRaw, hv_BlackLow, hv_BlackHigh);
  OpeningRectangle1(ho_RegionBlackRaw, &ho_RegionBlackOpen, hv_OpenSize, hv_OpenSize);

  Connection(ho_RegionBlackOpen, &ho_RegionBlackConnAll);
  SelectShape(ho_RegionBlackConnAll, &ho_RegionBlackValid, "area", "and", hv_MinBorderArea, 
      99999999);
  Union1(ho_RegionBlackValid, &ho_RegionBlackUnion);

  //---------- 定义四周搜索带 ----------
  GenRectangle1(&ho_BandLeft, 0, 0, hv_Height-1, (hv_Width*hv_BandLeftRatio).TupleRound());
  GenRectangle1(&ho_BandRight, 0, (hv_Width*(1.0-hv_BandRightRatio)).TupleRound(), 
      hv_Height-1, hv_Width-1);
  GenRectangle1(&ho_BandTop, 0, 0, (hv_Height*hv_BandTopRatio).TupleRound(), hv_Width-1);
  GenRectangle1(&ho_BandBottom, (hv_Height*(1.0-hv_BandBottomRatio)).TupleRound(), 
      0, hv_Height-1, hv_Width-1);

  //---------- 与四周搜索带求交 ----------
  Intersection(ho_RegionBlackUnion, ho_BandLeft, &ho_LeftCand);
  Intersection(ho_RegionBlackUnion, ho_BandRight, &ho_RightCand);
  Intersection(ho_RegionBlackUnion, ho_BandTop, &ho_TopCand);
  Intersection(ho_RegionBlackUnion, ho_BandBottom, &ho_BottomCand);

  Connection(ho_LeftCand, &ho_LeftConn);
  Connection(ho_RightCand, &ho_RightConn);
  Connection(ho_TopCand, &ho_TopConn);
  Connection(ho_BottomCand, &ho_BottomConn);

  SelectShape(ho_LeftConn, &ho_LeftSel, "area", "and", hv_MinBorderArea, 99999999);
  SelectShape(ho_RightConn, &ho_RightSel, "area", "and", hv_MinBorderArea, 99999999);
  SelectShape(ho_TopConn, &ho_TopSel, "area", "and", hv_MinBorderArea, 99999999);
  SelectShape(ho_BottomConn, &ho_BottomSel, "area", "and", hv_MinBorderArea, 99999999);

  CountObj(ho_LeftSel, &hv_LeftNum);
  CountObj(ho_RightSel, &hv_RightNum);
  CountObj(ho_TopSel, &hv_TopNum);
  CountObj(ho_BottomSel, &hv_BottomNum);

  //---------- 默认ROI ----------
  hv_ROI_Row1 = (hv_Height*hv_DefaultRow1Ratio).TupleRound();
  hv_ROI_Row2 = (hv_Height*hv_DefaultRow2Ratio).TupleRound();
  hv_ROI_Col1 = (hv_Width*hv_DefaultCol1Ratio).TupleRound();
  hv_ROI_Col2 = (hv_Width*hv_DefaultCol2Ratio).TupleRound();

  //---------- 左边界 ----------
  if (0 != (int(hv_LeftNum>0)))
  {
    SelectShapeStd(ho_LeftSel, &ho_LeftMax, "max_area", 70);
    SmallestRectangle1(ho_LeftMax, &hv_LR1, &hv_LC1, &hv_LR2, &hv_LC2);
    hv_ROI_Col1 = hv_LC2+hv_BorderMargin;
  }

  //---------- 右边界 ----------
  if (0 != (int(hv_RightNum>0)))
  {
    SelectShapeStd(ho_RightSel, &ho_RightMax, "max_area", 70);
    SmallestRectangle1(ho_RightMax, &hv_RR1, &hv_RC1, &hv_RR2, &hv_RC2);
    hv_ROI_Col2 = hv_RC1-hv_BorderMargin;
  }

  //---------- 上边界 ----------
  if (0 != (int(hv_TopNum>0)))
  {
    SelectShapeStd(ho_TopSel, &ho_TopMax, "max_area", 70);
    SmallestRectangle1(ho_TopMax, &hv_TR1, &hv_TC1, &hv_TR2, &hv_TC2);
    hv_ROI_Row1 = hv_TR2+hv_BorderMargin;
  }

  //---------- 下边界 ----------
  if (0 != (int(hv_BottomNum>0)))
  {
    SelectShapeStd(ho_BottomSel, &ho_BottomMax, "max_area", 70);
    SmallestRectangle1(ho_BottomMax, &hv_BR1, &hv_BC1, &hv_BR2, &hv_BC2);
    hv_ROI_Row2 = hv_BR1-hv_BorderMargin;
  }

  //---------- 边界保护 ----------
  if (0 != (int(hv_ROI_Row1<0)))
  {
    hv_ROI_Row1 = 0;
  }
  if (0 != (int(hv_ROI_Col1<0)))
  {
    hv_ROI_Col1 = 0;
  }
  if (0 != (int(hv_ROI_Row2>(hv_Height-1))))
  {
    hv_ROI_Row2 = hv_Height-1;
  }
  if (0 != (int(hv_ROI_Col2>(hv_Width-1))))
  {
    hv_ROI_Col2 = hv_Width-1;
  }

  //---------- 防止ROI反转或过小 ----------
  if (0 != (HTuple(HTuple(HTuple(int(hv_ROI_Row2<=hv_ROI_Row1)).TupleOr(int(hv_ROI_Col2<=hv_ROI_Col1))).TupleOr(int((hv_ROI_Row2-hv_ROI_Row1)<hv_MinROIHeight))).TupleOr(int((hv_ROI_Col2-hv_ROI_Col1)<hv_MinROIWidth))))
  {
    hv_ROI_Row1 = (hv_Height*hv_DefaultRow1Ratio).TupleRound();
    hv_ROI_Row2 = (hv_Height*hv_DefaultRow2Ratio).TupleRound();
    hv_ROI_Col1 = (hv_Width*hv_DefaultCol1Ratio).TupleRound();
    hv_ROI_Col2 = (hv_Width*hv_DefaultCol2Ratio).TupleRound();
    hv_IsFallback = 1;
  }

  //---------- 再做一次边界保护 ----------
  if (0 != (int(hv_ROI_Row1<0)))
  {
    hv_ROI_Row1 = 0;
  }
  if (0 != (int(hv_ROI_Col1<0)))
  {
    hv_ROI_Col1 = 0;
  }
  if (0 != (int(hv_ROI_Row2>(hv_Height-1))))
  {
    hv_ROI_Row2 = hv_Height-1;
  }
  if (0 != (int(hv_ROI_Col2>(hv_Width-1))))
  {
    hv_ROI_Col2 = hv_Width-1;
  }

  //---------- 生成ROI并真正裁图 ----------
  GenRectangle1(&ho_ROI_Middle, hv_ROI_Row1, hv_ROI_Col1, hv_ROI_Row2, hv_ROI_Col2);
  ReduceDomain(ho_Gray, ho_ROI_Middle, &ho_GrayROI_Domain);
  CropDomain(ho_GrayROI_Domain, &(*ho_GrayROI));

  HTuple  hv_FullROIWidth, hv_SplitCol;
  HObject  ho_ROI_Left, ho_ROI_Right, ho_LeftGrayROI_Domain, ho_RightGrayROI_Domain;

  hv_FullROIWidth = (hv_ROI_Col2-hv_ROI_Col1)+1;
  hv_SplitCol = (hv_ROI_Col1+(hv_FullROIWidth/2.0).TupleFloor())-1;
  if (0 != (int(hv_SplitCol<=hv_ROI_Col1)))
  {
    hv_SplitCol = hv_ROI_Col1+1;
  }
  if (0 != (int(hv_SplitCol>=hv_ROI_Col2)))
  {
    hv_SplitCol = hv_ROI_Col2-1;
  }

  GenRectangle1(&ho_ROI_Left, hv_ROI_Row1, hv_ROI_Col1, hv_ROI_Row2, hv_SplitCol);
  GenRectangle1(&ho_ROI_Right, hv_ROI_Row1, hv_SplitCol+1, hv_ROI_Row2, hv_ROI_Col2);
  ReduceDomain(ho_Gray, ho_ROI_Left, &ho_LeftGrayROI_Domain);
  CropDomain(ho_LeftGrayROI_Domain, &(*ho_LeftGrayROI));
  ReduceDomain(ho_Gray, ho_ROI_Right, &ho_RightGrayROI_Domain);
  CropDomain(ho_RightGrayROI_Domain, &(*ho_RightGrayROI));
}

#ifndef NO_EXPORT_MAIN
// Main procedure 
void action()
{

  // Local iconic variables
  HObject  ho_Image, ho_GrayROI, ho_LeftGrayROI, ho_RightGrayROI, ho_DebugImage;

  // Local control variables
  HTuple  hv_InputDir, hv_OutputDir, hv_DebugDir;
  HTuple  hv_OutExist, hv_DebugExist, hv_AllFiles, hv_ImageFiles;
  HTuple  hv_NumFiles, hv_WindowOpened, hv_Index, hv_FileName;
  HTuple  hv_WindowHandle;

  dev_update_off();
  if (HDevWindowStack::IsOpen())
    CloseWindow(HDevWindowStack::Pop());

  //============================================
  //路径设置
  //============================================
  hv_InputDir = //'D:/Project/半导体缺陷检测/image'
      "D:/Project/\260\353\265\274\314\345\310\261\317\335\274\354\262\342/image";
  hv_OutputDir = //'D:/Project/半导体缺陷检测/test_images_out/'
      "D:/Project/\260\353\265\274\314\345\310\261\317\335\274\354\262\342/test_images_out/";
  hv_DebugDir = hv_OutputDir+"/debug";

  //输出目录不存在就创建
  FileExists(hv_OutputDir, &hv_OutExist);
  if (0 != (int(hv_OutExist==0)))
  {
    MakeDir(hv_OutputDir);
  }

  FileExists(hv_DebugDir, &hv_DebugExist);
  if (0 != (int(hv_DebugExist==0)))
  {
    MakeDir(hv_DebugDir);
  }

  //============================================
  //搜索图片文件
  //============================================
  ListFiles(hv_InputDir, (HTuple("files").Append("recursive")), &hv_AllFiles);
  TupleRegexpSelect(hv_AllFiles, "(?i).*\\.(bmp|png|jpg|jpeg|tif|tiff)$", &hv_ImageFiles);

  hv_NumFiles = hv_ImageFiles.TupleLength();

  if (0 != (int(hv_NumFiles==0)))
  {
    // stop(...); only in hdevelop
  }

  //============================================
  //可视化窗口（可选）
  //============================================
  hv_WindowOpened = 0;

  //============================================
  //批量处理
  //============================================
  {
  HTuple end_val41 = hv_NumFiles-1;
  HTuple step_val41 = 1;
  for (hv_Index=0; hv_Index.Continue(end_val41, step_val41); hv_Index += step_val41)
  {

    hv_FileName = HTuple(hv_ImageFiles[hv_Index]);
    ReadImage(&ho_Image, hv_FileName);

    //调用本地过程
    Preprocess_Gray(ho_Image, &ho_GrayROI, &ho_LeftGrayROI, &ho_RightGrayROI);



    //保存裁剪图
    WriteImage(ho_GrayROI, "bmp", 0, (hv_OutputDir+hv_Index)+"_crop.bmp");
    WriteImage(ho_LeftGrayROI, "bmp", 0, (hv_OutputDir+hv_Index)+"_left_crop.bmp");
    WriteImage(ho_RightGrayROI, "bmp", 0, (hv_OutputDir+hv_Index)+"_right_crop.bmp");

    //保存debug图（原图 + ROI框）
    if (0 != (int(hv_WindowOpened==0)))
    {
      dev_open_window_fit_image(ho_Image, 0, 0, -1, -1, &hv_WindowHandle);
      hv_WindowOpened = 1;
    }

    if (HDevWindowStack::IsOpen())
      DispObj(ho_Image, HDevWindowStack::GetActive());
    if (HDevWindowStack::IsOpen())
      SetColor(HDevWindowStack::GetActive(),"green");
    if (HDevWindowStack::IsOpen())
      SetDraw(HDevWindowStack::GetActive(),"margin");
    if (HDevWindowStack::IsOpen())
      SetLineWidth(HDevWindowStack::GetActive(),3);
    if (HDevWindowStack::IsOpen())
      DispObj(ho_GrayROI, HDevWindowStack::GetActive());

    DumpWindowImage(&ho_DebugImage, hv_WindowHandle);
    WriteImage(ho_DebugImage, "bmp", 0, (hv_DebugDir+hv_Index)+"_debug");


  }
  }
}


#ifndef NO_EXPORT_APP_MAIN


int main(int argc, char *argv[])
{
  int ret = 0;

  try
  {
#if defined(_WIN32)
    SetSystem("use_window_thread", "true");
#endif

    // file was stored with local-8-bit encoding
    //   -> set the interface encoding accordingly
    SetHcppInterfaceStringEncodingIsUtf8(false);

    // Default settings used in HDevelop (can be omitted)
    SetSystem("width", 512);
    SetSystem("height", 512);

    action();
  }
  catch (HException &exception)
  {
    fprintf(stderr,"  Error #%u in %s: %s\n", exception.ErrorCode(),
            exception.ProcName().TextA(),
            exception.ErrorMessage().TextA());
    ret = 1;
  }

#if defined(_WIN32)
  // On Windows socket communication is no longer possible after returning
  // from main, so HALCON cannot return floating licenses automatically.
  try
  {
    SetSystem("return_license", "true");
  }
  catch (...)
  {
    // Ignore any errors that might occur when returning the license.
  }
#endif

  return ret;
}

#endif


#endif



